apiVersion: v1
kind: Service
metadata:
  name: blogify-app
  namespace: blogify-dev
spec:
  type: NodePort
  selector:
    app: blogify-app
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30080