apiVersion: v1
kind: Secret
metadata:
  name: blogify-secrets
  namespace: blogify-dev
type: Opaque
stringData: 
  MONGO_URL: "mongodb+srv://vatniavdhut14_db_user:vK87Org7hXexesvO@cluster0.uq5tvv0.mongodb.net/?appName=Cluster0"
  JWT_SECRET: "@v@14321"